export const REQUEST_SAVE_INFO = 'REQUEST_SAVE_INFO'

export const REQUEST_CREATE_REQUEST = 'REQUEST_CREATE_REQUEST'
export const REQUEST_CREATE_SUCCESS = 'REQUEST_CREATE_SUCCESS'
export const REQUEST_CREATE_FAIL = 'REQUEST_CREATE_FAIL'
export const REQUEST_CREATE_RESET = 'REQUEST_CREATE_RESET'

export const REQUEST_ADD_ITEM = 'REQUEST_ADD_ITEM'
